// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyCuaHangTienLoi.Data;

namespace QuanLyCuaHangTienLoi.Data.Migrations
{
    [DbContext(typeof(CuaHangTienLoiDbContext))]
    partial class CuaHangTienLoiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("NhaCungCapSanPham", b =>
                {
                    b.Property<Guid>("NhaCungCapsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SanPhamsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("NhaCungCapsId", "SanPhamsId");

                    b.HasIndex("SanPhamsId");

                    b.ToTable("NhaCungCapSanPham");
                });

            modelBuilder.Entity("QuanLyCuaHangTienLoi.Data.Models.ChiTietHoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<Guid>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LoSanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("LoSanPhamId");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("QuanLyCuaHangTienLoi.Data.Models.DonViSanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenDonViSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DonViSanPhams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("592657c2-c52f-4014-a671-e6483232de44"),
                            TenDonViSanPham = "Hộp"
                        },
                        new
                        {
                            Id = new Guid("e56b3513-7b1d-4951-867b-8c7532390a7b"),
                            TenDonViSanPham = "Chai"
                        },
                        new
                        {
                            Id = new Guid("25e5bb3a-0bc8-4ec1-b0f2-388a69ae5b33"),
                            TenDonViSanPham = "Lon"
                        },
                        new
                        {
                            Id = new Guid("3433f265-232d-4e0c-bcdd-91d4de6454ed"),
                            TenDonViSanPham = "Thùng"
                        },
                        new
                        {
                            Id = new Guid("65e8e640-bee2-4772-9eec-811132d09c62"),
                            TenDonViSanPham = "Gói"
                        });
                });

            modelBuilder.Entity("QuanLyCuaHangTienLoi.Data.Models.GiamGia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhanTramGiamGia")
                        .HasColumnType("int");

                    b.Property<Guid>("SanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SanPhamId");

                    b.ToTable("GiamGias");
                });

            modelBuilder.Entity("QuanLyCuaHangTienLoi.Data.Models.HoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KhachHangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NhanVienId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("QuanLyCuaHangTienLoi.Data.Models.KeHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Cot")
                        .HasColumnType("bigint");

                    b.Property<long>("Hang")
                        .HasColumnType("bigint");

                    b.Property<long>("Ke")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SanPhamId");

                    b.ToTable("KeHangs");
                });

            modelBuilder.Entity("QuanLyCuaHangTienLoi.Data.Models.KhachHang", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KhachHangs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Email = "",
                            IsActive = false,
                            SoDienThoai = "",
                            TenKhachHang = "Ko co khach hang"
                        },
                        new
                        {
                            Id = new Guid("7e3a16bf-ff86-4569-9f85-ae74990635de"),
                            Email = "buddblackston@email.com",
                            IsActive = false,
                            SoDienThoai = "450-52-6781",
                            TenKhachHang = "Budd Blackston"
                        },
                        new
                        {
                            Id = new Guid("8b702d4f-a0b5-4615-a3a6-df2ddeeba7f7"),
                            Email = "alidasommerled@email.com",
                            IsActive = false,
                            SoDienThoai = "798-91-4772",
                            TenKhachHang = "Alida Sommerled"
                        },
                        new
                        {
                            Id = new Guid("1c2df9bb-1133-44a4-9e85-781032e8e43e"),
                            Email = "georascraggs@email.com",
                            IsActive = false,
                            SoDienThoai = "455-12-4139",
                            TenKhachHang = "Georas Craggs"
                        },
                        new
                        {
                            Id = new Guid("668fed87-4abd-49c9-a414-78194421e705"),
                            Email = "aguistinstembridge@email.com",
                            IsActive = false,
                            SoDienThoai = "162-12-4841",
                            TenKhachHang = "Aguistin Stembridge"
                        },
                        new
                        {
                            Id = new Guid("4e463bff-8b71-4af9-97bb-f4b4af591632"),
                            Email = "demottenevold@email.com",
                            IsActive = false,
                            SoDienThoai = "737-02-8831",
                            TenKhachHang = "Demott Enevold"
                        });
                });

            modelBuilder.Entity("QuanLyCuaHangTienLoi.Data.Models.LoSanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NhaCungCapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NhaCungCapId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("LoSanPhams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b7be68c6-42fa-4518-881d-d896de46e5d5"),
                            NgayNhap = new DateTime(2020, 12, 20, 1, 13, 49, 578, DateTimeKind.Local).AddTicks(2434),
                            NhaCungCapId = new Guid("0ec1ab8f-8d70-409b-9b11-efb27284c4a0"),
                            SanPhamId = new Guid("75fbb1ed-bdd0-403c-8d24-e85d74e11945"),
                            SoLuong = 20
                        },
                        new
                        {
                            Id = new Guid("edf5e49f-53ac-4174-aedc-cd1de2255b3f"),
                            NgayNhap = new DateTime(2020, 12, 20, 1, 13, 49, 579, DateTimeKind.Local).AddTicks(3837),
                            NhaCungCapId = new Guid("0ec1ab8f-8d70-409b-9b11-efb27284c4a0"),
                            SanPhamId = new Guid("62e4e3d4-6534-4a95-b243-a81732f9a74e"),
                            SoLuong = 20
                        },
                        new
                        {
                            Id = new Guid("dae7938b-ecb4-4db7-89af-f1627280a814"),
                            NgayNhap = new DateTime(2020, 12, 20, 1, 13, 49, 579, DateTimeKind.Local).AddTicks(3943),
                            NhaCungCapId = new Guid("02418cb3-ed16-469d-869b-37aead548c84"),
                            SanPhamId = new Guid("13e407fc-a55d-4c56-8f2a-85ea63a48523"),
                            SoLuong = 20
                        },
                        new
                        {
                            Id = new Guid("f593cec4-78b2-4e0e-9a63-9b47a15949f2"),
                            NgayNhap = new DateTime(2020, 12, 20, 1, 13, 49, 579, DateTimeKind.Local).AddTicks(3949),
                            NhaCungCapId = new Guid("02418cb3-ed16-469d-869b-37aead548c84"),
                            SanPhamId = new Guid("d2646916-48aa-4e65-9974-3c8356681d0d"),
                            SoLuong = 20
                        },
                        new
                        {
                            Id = new Guid("c99af59c-49cd-4cbd-aedd-3292b2741ba0"),
                            NgayNhap = new DateTime(2020, 12, 20, 1, 13, 49, 579, DateTimeKind.Local).AddTicks(3951),
                            NhaCungCapId = new Guid("fbc4aff7-1b71-4f29-9d04-6e5a2030cdc9"),
                            SanPhamId = new Guid("49edbe65-ddf6-44ad-8a62-78b45a530ee0"),
                            SoLuong = 20
                        },
                        new
                        {
                            Id = new Guid("1001266c-87fe-4732-b70a-dc15ac8bbba5"),
                            NgayNhap = new DateTime(2020, 12, 20, 1, 13, 49, 579, DateTimeKind.Local).AddTicks(3961),
                            NhaCungCapId = new Guid("fbc4aff7-1b71-4f29-9d04-6e5a2030cdc9"),
                            SanPhamId = new Guid("0113a4dc-2390-4ad1-b909-66f89e2352fb"),
                            SoLuong = 20
                        },
                        new
                        {
                            Id = new Guid("8b21c13c-f7c3-4674-86f3-40457dbd8073"),
                            NgayNhap = new DateTime(2020, 12, 20, 1, 13, 49, 579, DateTimeKind.Local).AddTicks(3963),
                            NhaCungCapId = new Guid("03a9cf4f-6efa-480e-b3c8-c298298df715"),
                            SanPhamId = new Guid("ed6cb8d4-429a-4fb8-8291-4fc3fae8b74d"),
                            SoLuong = 20
                        },
                        new
                        {
                            Id = new Guid("4db6517f-531c-45b7-8ab4-97fb6d67499c"),
                            NgayNhap = new DateTime(2020, 12, 20, 1, 13, 49, 579, DateTimeKind.Local).AddTicks(3976),
                            NhaCungCapId = new Guid("03a9cf4f-6efa-480e-b3c8-c298298df715"),
                            SanPhamId = new Guid("8383c50d-9583-4d5b-a253-fe3f9199bf36"),
                            SoLuong = 20
                        },
                        new
                        {
                            Id = new Guid("7e36f13a-9be0-4504-a2f7-ee3db818d48f"),
                            NgayNhap = new DateTime(2020, 12, 20, 1, 13, 49, 579, DateTimeKind.Local).AddTicks(3979),
                            NhaCungCapId = new Guid("ae5fc190-a606-4e3d-a96e-2c6dd22dacc1"),
                            SanPhamId = new Guid("9fac33d0-dae0-4d88-84f7-ea5bca2254b3"),
                            SoLuong = 20
                        },
                        new
                        {
                            Id = new Guid("8ebfc259-6d66-4c79-a632-a08de4a6c1ef"),
                            NgayNhap = new DateTime(2020, 12, 20, 1, 13, 49, 579, DateTimeKind.Local).AddTicks(3983),
                            NhaCungCapId = new Guid("ae5fc190-a606-4e3d-a96e-2c6dd22dacc1"),
                            SanPhamId = new Guid("f57153a0-2f1f-4733-a332-97ee6961e4f3"),
                            SoLuong = 20
                        });
                });

            modelBuilder.Entity("QuanLyCuaHangTienLoi.Data.Models.LoaiSanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenLoaiSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoaiSanPhams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("347d242a-7028-4b64-9165-7fa0334050a9"),
                            TenLoaiSanPham = "Nước ngọt"
                        },
                        new
                        {
                            Id = new Guid("4f8976b6-770f-4c92-84aa-730d013ac187"),
                            TenLoaiSanPham = "Bánh kẹo"
                        },
                        new
                        {
                            Id = new Guid("f378b558-0e08-4db4-9d44-fd7efebc849e"),
                            TenLoaiSanPham = "Rau quả"
                        },
                        new
                        {
                            Id = new Guid("3482ac8c-9dea-4727-aa16-2ad90182457d"),
                            TenLoaiSanPham = "Thịt"
                        },
                        new
                        {
                            Id = new Guid("530293c4-bca8-4429-9df4-d0827c3a83b7"),
                            TenLoaiSanPham = "Đồ sữa"
                        });
                });

            modelBuilder.Entity("QuanLyCuaHangTienLoi.Data.Models.NhaCungCap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenNhaCungCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThongTinLienHe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NhaCungCaps");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0ec1ab8f-8d70-409b-9b11-efb27284c4a0"),
                            TenNhaCungCap = "Topiczoom"
                        },
                        new
                        {
                            Id = new Guid("02418cb3-ed16-469d-869b-37aead548c84"),
                            TenNhaCungCap = "Thoughtmix"
                        },
                        new
                        {
                            Id = new Guid("fbc4aff7-1b71-4f29-9d04-6e5a2030cdc9"),
                            TenNhaCungCap = "Gigaclub"
                        },
                        new
                        {
                            Id = new Guid("03a9cf4f-6efa-480e-b3c8-c298298df715"),
                            TenNhaCungCap = "Vinder"
                        },
                        new
                        {
                            Id = new Guid("ae5fc190-a606-4e3d-a96e-2c6dd22dacc1"),
                            TenNhaCungCap = "Dynazzy"
                        });
                });

            modelBuilder.Entity("QuanLyCuaHangTienLoi.Data.Models.NhanVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Matkhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NhanViens");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7b5c2d90-7798-4227-9f1c-637bb3a19bda"),
                            IsActive = false,
                            Matkhau = "1a2eb4b4",
                            TenNhanVien = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("741faa63-e6ac-4cce-b0c9-4676ba4d78fe"),
                            IsActive = false,
                            Matkhau = "14165849",
                            TenNhanVien = "Minette Eallis",
                            Username = "minetteeallis"
                        },
                        new
                        {
                            Id = new Guid("879603fe-211d-41f4-b877-78795c40d423"),
                            IsActive = false,
                            Matkhau = "83b3acf6",
                            TenNhanVien = "Kacie Phettis",
                            Username = "kaciephettis"
                        },
                        new
                        {
                            Id = new Guid("af251ac8-a93b-4e7f-aef3-900d8298fc2e"),
                            IsActive = false,
                            Matkhau = "fc4fb722",
                            TenNhanVien = "Erinn King",
                            Username = "erinnking"
                        },
                        new
                        {
                            Id = new Guid("527f86c2-520f-4a0c-803f-6dc9a68438a8"),
                            IsActive = false,
                            Matkhau = "6aaac2a0",
                            TenNhanVien = "Nanci Pain",
                            Username = "nancipain"
                        });
                });

            modelBuilder.Entity("QuanLyCuaHangTienLoi.Data.Models.SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DonViSanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("GiaTien")
                        .HasColumnType("float");

                    b.Property<Guid>("LoaiSanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DonViSanPhamId");

                    b.HasIndex("LoaiSanPhamId");

                    b.ToTable("SanPhams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("75fbb1ed-bdd0-403c-8d24-e85d74e11945"),
                            DonViSanPhamId = new Guid("592657c2-c52f-4014-a671-e6483232de44"),
                            GiaTien = 37000.0,
                            LoaiSanPhamId = new Guid("347d242a-7028-4b64-9165-7fa0334050a9"),
                            TenSanPham = "Beans - Wax"
                        },
                        new
                        {
                            Id = new Guid("62e4e3d4-6534-4a95-b243-a81732f9a74e"),
                            DonViSanPhamId = new Guid("592657c2-c52f-4014-a671-e6483232de44"),
                            GiaTien = 13000.0,
                            LoaiSanPhamId = new Guid("347d242a-7028-4b64-9165-7fa0334050a9"),
                            TenSanPham = "Swordfish Loin Portions"
                        },
                        new
                        {
                            Id = new Guid("13e407fc-a55d-4c56-8f2a-85ea63a48523"),
                            DonViSanPhamId = new Guid("e56b3513-7b1d-4951-867b-8c7532390a7b"),
                            GiaTien = 11000.0,
                            LoaiSanPhamId = new Guid("4f8976b6-770f-4c92-84aa-730d013ac187"),
                            TenSanPham = "Bagels Poppyseed"
                        },
                        new
                        {
                            Id = new Guid("d2646916-48aa-4e65-9974-3c8356681d0d"),
                            DonViSanPhamId = new Guid("e56b3513-7b1d-4951-867b-8c7532390a7b"),
                            GiaTien = 38000.0,
                            LoaiSanPhamId = new Guid("4f8976b6-770f-4c92-84aa-730d013ac187"),
                            TenSanPham = "Tofu - Firm"
                        },
                        new
                        {
                            Id = new Guid("49edbe65-ddf6-44ad-8a62-78b45a530ee0"),
                            DonViSanPhamId = new Guid("25e5bb3a-0bc8-4ec1-b0f2-388a69ae5b33"),
                            GiaTien = 25000.0,
                            LoaiSanPhamId = new Guid("f378b558-0e08-4db4-9d44-fd7efebc849e"),
                            TenSanPham = "Wine - Jaboulet Cotes Du Rhone"
                        },
                        new
                        {
                            Id = new Guid("0113a4dc-2390-4ad1-b909-66f89e2352fb"),
                            DonViSanPhamId = new Guid("25e5bb3a-0bc8-4ec1-b0f2-388a69ae5b33"),
                            GiaTien = 33000.0,
                            LoaiSanPhamId = new Guid("f378b558-0e08-4db4-9d44-fd7efebc849e"),
                            TenSanPham = "Spice - Onion Powder Granulated"
                        },
                        new
                        {
                            Id = new Guid("ed6cb8d4-429a-4fb8-8291-4fc3fae8b74d"),
                            DonViSanPhamId = new Guid("3433f265-232d-4e0c-bcdd-91d4de6454ed"),
                            GiaTien = 31000.0,
                            LoaiSanPhamId = new Guid("3482ac8c-9dea-4727-aa16-2ad90182457d"),
                            TenSanPham = "Evaporated Milk - Skim"
                        },
                        new
                        {
                            Id = new Guid("8383c50d-9583-4d5b-a253-fe3f9199bf36"),
                            DonViSanPhamId = new Guid("3433f265-232d-4e0c-bcdd-91d4de6454ed"),
                            GiaTien = 13000.0,
                            LoaiSanPhamId = new Guid("3482ac8c-9dea-4727-aa16-2ad90182457d"),
                            TenSanPham = "Squash - Guords"
                        },
                        new
                        {
                            Id = new Guid("9fac33d0-dae0-4d88-84f7-ea5bca2254b3"),
                            DonViSanPhamId = new Guid("65e8e640-bee2-4772-9eec-811132d09c62"),
                            GiaTien = 45000.0,
                            LoaiSanPhamId = new Guid("530293c4-bca8-4429-9df4-d0827c3a83b7"),
                            TenSanPham = "Filter - Coffee"
                        },
                        new
                        {
                            Id = new Guid("f57153a0-2f1f-4733-a332-97ee6961e4f3"),
                            DonViSanPhamId = new Guid("65e8e640-bee2-4772-9eec-811132d09c62"),
                            GiaTien = 47000.0,
                            LoaiSanPhamId = new Guid("530293c4-bca8-4429-9df4-d0827c3a83b7"),
                            TenSanPham = "Beer - Paulaner Hefeweisse"
                        });
                });

            modelBuilder.Entity("NhaCungCapSanPham", b =>
                {
                    b.HasOne("QuanLyCuaHangTienLoi.Data.Models.NhaCungCap", null)
                        .WithMany()
                        .HasForeignKey("NhaCungCapsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangTienLoi.Data.Models.SanPham", null)
                        .WithMany()
                        .HasForeignKey("SanPhamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuanLyCuaHangTienLoi.Data.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("QuanLyCuaHangTienLoi.Data.Models.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDon")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangTienLoi.Data.Models.LoSanPham", "LoSanPham")
                        .WithMany()
                        .HasForeignKey("LoSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("LoSanPham");
                });

            modelBuilder.Entity("QuanLyCuaHangTienLoi.Data.Models.GiamGia", b =>
                {
                    b.HasOne("QuanLyCuaHangTienLoi.Data.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("QuanLyCuaHangTienLoi.Data.Models.HoaDon", b =>
                {
                    b.HasOne("QuanLyCuaHangTienLoi.Data.Models.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangTienLoi.Data.Models.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyCuaHangTienLoi.Data.Models.KeHang", b =>
                {
                    b.HasOne("QuanLyCuaHangTienLoi.Data.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("QuanLyCuaHangTienLoi.Data.Models.LoSanPham", b =>
                {
                    b.HasOne("QuanLyCuaHangTienLoi.Data.Models.NhaCungCap", "NhaCungCap")
                        .WithMany("LoSanPhams")
                        .HasForeignKey("NhaCungCapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangTienLoi.Data.Models.SanPham", "SanPham")
                        .WithMany("LoSanPhams")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaCungCap");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("QuanLyCuaHangTienLoi.Data.Models.SanPham", b =>
                {
                    b.HasOne("QuanLyCuaHangTienLoi.Data.Models.DonViSanPham", "DonViSanPham")
                        .WithMany("SanPhams")
                        .HasForeignKey("DonViSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyCuaHangTienLoi.Data.Models.LoaiSanPham", "LoaiSanPham")
                        .WithMany("SanPhams")
                        .HasForeignKey("LoaiSanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonViSanPham");

                    b.Navigation("LoaiSanPham");
                });

            modelBuilder.Entity("QuanLyCuaHangTienLoi.Data.Models.DonViSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("QuanLyCuaHangTienLoi.Data.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDon");
                });

            modelBuilder.Entity("QuanLyCuaHangTienLoi.Data.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("QuanLyCuaHangTienLoi.Data.Models.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("QuanLyCuaHangTienLoi.Data.Models.NhaCungCap", b =>
                {
                    b.Navigation("LoSanPhams");
                });

            modelBuilder.Entity("QuanLyCuaHangTienLoi.Data.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("QuanLyCuaHangTienLoi.Data.Models.SanPham", b =>
                {
                    b.Navigation("LoSanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
